# Generated by Django 4.2.13 on 2026-05-26 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('audio_url', models.URLField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('radius_meters', models.PositiveIntegerField(default=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'geo_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='geo_notes_latitud_108c44_idx')],
            },
        ),
    ]
